platform :ios, '7.0'

target 'kuaibov' do
    
    pod 'AFNetworking','~> 2.6.0'
    #pod 'FMDB'
    pod 'Masonry', '~> 0.6.2'
    pod 'SDWebImage', '~> 3.7.3'
    pod 'MBProgressHUD', '~> 0.9.1'
    #pod 'SIAlertView'
    pod 'MJRefresh', '~> 2.4.7'
    pod 'SFHFKeychainUtils', '~> 0.0.1'
    pod 'OpenSSL', '~> 1.0.204'
    pod 'BlocksKit', '~> 2.2.5'
    
    # Github page: https://github.com/steipete/Aspects
    pod 'Aspects','~>1.4.1'
    pod 'SDCycleScrollView', '~> 1.3'
    
    # For BaiduMobAdWall
    pod 'TouchJSON', '~> 1.1'
    pod 'OpenUDID', '~> 1.0.0'
    pod 'FMDB', '~> 2.6.2'
    pod 'XMLReader-Arc', '~> 1.1'
    
end